### ISSUE TITLE
再定義と再代入について

### ISSUE THREAD

**Issue by rakuda-daraku** [js-workshop-sapporo/document#2]
https://github.com/js-workshop-sapporo/document/edit/master/1st/README.md#L123
ここは `再代入` ではなく、 `再定義` が用語としては正しいような気がしますがどうでしょうか？

<img width="488" alt="スクリーンショット 2019-07-04 10 20 11" src="https://user-images.githubusercontent.com/7471680/60633505-eb5a3380-9e45-11e9-90a5-6038975e26c5.png">

**Comment by nagasawaaaa** [comment]
@rakuda-daraku 
おっしゃる通りかと思います！

**Comment by rakuda-daraku** [comment]
#3 Merge されたのでClose
